import { test,expect } from "@playwright/test";
import { resolve } from "node:path";

test("Business central: edição Owner propaga ao contato público e sobrevive ao reload",async({page,request})=>{
 const api="http://127.0.0.1:17333";
 await page.goto("/?audit=intro-clean");
 await expect(page.locator(".intro-visual-carousel")).toHaveCount(0);
 await expect(page.locator(".brand-panel img")).toHaveCount(0);
 const owner=await request.post(api+"/admin/login",{data:{name:"Fabio0",identifier:"5571999990001",groupCode:"#",secret:"e2e-owner-secret-32-characters-long"}});
 expect(owner.ok()).toBe(true);
 await page.evaluate(token=>{localStorage.setItem("conexao_owner_token",token);localStorage.setItem("conexao_active_role","owner");},(await owner.json()).token);
 await page.reload();
 await page.getByRole("button",{name:"Configurar integração",exact:true}).click();
 const modal=page.getByRole("dialog",{name:"Configurar integração WhatsApp"});
 const number=page.getByLabel("Número do WhatsApp Business",{exact:true});
 await expect(number).toHaveValue("+5571993978956");
 await number.scrollIntoViewIfNeeded();
 await page.screenshot({path:resolve("../../docs/evidencias/business-numero-desktop.png"),fullPage:true});
 await page.getByRole("button",{name:"Explicar número Business e atualização dos links"}).click();
 await expect(page.getByRole("dialog",{name:"Número público do SOS YouTuber"})).toBeVisible();
 await page.keyboard.press("Escape");
 await expect(modal).toBeVisible();
 await number.fill("+55 (71) 99999-9090");
 await page.getByRole("button",{name:"Salvar configuração",exact:true}).click();
 await expect(page.getByText("Configuração salva. Para ativar o canal Meta ainda falta a credencial de acesso.",{exact:true})).toBeVisible();
 expect((await (await request.get(api+"/public/groups")).json()).whatsappJoinUrl).toContain("wa.me/5571999999090");
 await page.reload();
 await page.getByRole("button",{name:"Configurar integração",exact:true}).click();
 await expect(number).toHaveValue("+5571999999090");
 await page.setViewportSize({width:390,height:844});
 await number.scrollIntoViewIfNeeded();
 expect(await modal.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 expect(await page.evaluate(()=>getComputedStyle(document.body).overflow)).toBe("hidden");
 await number.fill("+55 71 99397-8956");
 await page.getByRole("button",{name:"Salvar configuração",exact:true}).click();
 await expect(number).toHaveValue("+5571993978956");
 expect((await (await request.get(api+"/public/groups")).json()).whatsappJoinUrl).toContain("wa.me/5571993978956");
 await number.scrollIntoViewIfNeeded();
 await page.screenshot({path:resolve("../../docs/evidencias/business-numero-mobile.png"),fullPage:true});
 await page.keyboard.press("Escape");
 await expect(modal).toHaveCount(0);
 expect(await page.evaluate(()=>getComputedStyle(document.body).overflow)).not.toBe("hidden");
});
