import { test, expect } from "@playwright/test";
import { resolve } from "node:path";

test("login único, solicitação, aprovação Owner, participante e compra demo", async ({ page, request }) => {
  const evidence = resolve("../../docs/evidencias"), errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/");
  await expect(page.getByRole("heading", { name: "Entre na sua conexão" })).toBeVisible();
  await page.screenshot({ path: resolve(evidence, "login-mobile.png"), fullPage: true });
  await page.getByRole("button", { name: "Quero participar!", exact: true }).click();
  await page.getByLabel("Seu nome ou como prefere ser chamado").fill("Pessoa E2E");
  await page.getByLabel("Número do WhatsApp").fill("5571900000001");
  await page.getByLabel("Grupo SOS YOUTUBER").fill("1");
  await page.getByRole("checkbox").check(); await page.getByRole("button", { name: "Solicitar participação" }).click();
  await expect(page.getByText("Solicitação registrada.", { exact: false })).toBeVisible();
  await page.screenshot({ path: resolve(evidence, "solicitacao-mobile.png"), fullPage: true });
  await page.getByRole("button", { name: "Voltar ao login" }).click();
  await page.getByLabel("Seu nome ou como prefere ser chamado").fill("Fabio0"); await page.getByLabel("Grupo SOS YOUTUBER").fill("#");
  await page.getByLabel("WhatsApp / identificador do Owner").fill("+55 71 [9]9999-0001");
  await page.getByLabel("Credencial do Owner").fill("e2e-owner-secret-32-characters-long");
  await page.getByRole("button", { name: "Entrar como Owner" }).click();
  await expect(page.getByRole("heading", { name: "Sua conexão, em números." })).toBeVisible();
  await expect(page.getByText("Pessoa E2E", { exact: true })).toBeVisible();
  await page.screenshot({ path: resolve(evidence, "owner-mobile.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
  await page.getByRole("button", { name: "Aprovar", exact: true }).click();
  await expect(page.getByText("Solicitação aprovada.", { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: resolve(evidence, "owner-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: /Fabio0/ }).click();
  await page.getByLabel("Seu nome ou como prefere ser chamado").fill("Pessoa E2E"); await page.getByLabel("Número do WhatsApp").fill("5571900000001");
  await page.getByLabel("Grupo SOS YOUTUBER").fill("1"); await page.getByRole("button", { name: "Receber código" }).click();
  const code = await page.locator(".dev-code strong").innerText();
  await page.getByLabel("Código de 6 dígitos").fill(code); await page.getByRole("button", { name: "Entrar no quadro" }).click();
  await expect(page.getByRole("heading", { name: "Vamos montar a próxima seleção?" })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByPlaceholder("Cole a URL do seu vídeo no YouTube").fill("https://youtu.be/dQw4w9WgXcQ");
  await page.getByRole("button", { name: "Salvar no espaço 1" }).click();
  await expect(page.getByText("Você já participou deste ciclo.", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Comprar créditos" }).click();
  await page.getByLabel("E-mail do pagador").fill("e2e@example.com"); await page.getByLabel("CPF do pagador").fill("12345678901");
  await page.getByRole("button", { name: "Gerar Pix" }).click(); await page.getByRole("button", { name: "Simular aprovação" }).click();
  await expect(page.getByText("Pagamento confirmado:", { exact: false })).toBeVisible();
  await page.getByPlaceholder("Cole a URL do seu vídeo no YouTube").fill("https://youtu.be/9bZkp7q19f0");
  await page.getByRole("button", { name: "Salvar no espaço 2" }).click();
  await expect(page.getByText("2 de 10 vídeos", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
  await page.screenshot({ path: resolve(evidence, "participante-mobile.png"), fullPage: true });
  const owner = await request.post("http://127.0.0.1:17333/admin/login", { data: { name: "Fabio0", identifier: "+55 71 [9]9999-0001", groupCode: "#", secret: "e2e-owner-secret-32-characters-long" } });
  expect(owner.ok()).toBeTruthy(); const ownerToken = (await owner.json()).token;
  for (let n = 3; n <= 10; n++) {
    const phone = `55719000000${String(n).padStart(2, "0")}`;
    const member = await request.post("http://127.0.0.1:17333/admin/members", { headers: { authorization: `Bearer ${ownerToken}` }, data: { phone, groupCode: n % 2 ? "1" : "2" } }); expect(member.ok()).toBeTruthy();
    const code = await request.post("http://127.0.0.1:17333/auth/request-code", { data: { name: `Participante ${n}`, phone, groupCode: n % 2 ? "1" : "2" } }); expect(code.ok()).toBeTruthy();
    const login = await request.post("http://127.0.0.1:17333/auth/verify", { data: { phone, code: (await code.json()).devCode } }); expect(login.ok()).toBeTruthy();
    const token = (await login.json()).token;
    const shared = await request.get("http://127.0.0.1:17333/dashboard", { headers: { authorization: `Bearer ${token}` } });
    expect((await shared.json()).openRound.slots[0].userName).toBe("Pessoa E2E");
    const saved = await request.post("http://127.0.0.1:17333/rounds/current/submissions", { headers: { authorization: `Bearer ${token}` }, data: { url: `https://youtu.be/E2Evideo${String(n).padStart(3,"0")}` } }); expect(saved.status()).toBe(201);
  }
  await page.reload(); await expect(page.getByRole("heading", { name: "10 vídeos prontos para sua playlist" })).toBeVisible();
  await page.getByText("Ver os 10 vídeos, autores e horários", { exact: true }).click();
  await expect(page.locator(".cycle-details .slot.filled")).toHaveCount(10);
  await expect(page.locator(".cycle-details").getByRole("button", { name: "Criar playlist" })).toHaveCount(2);
  await expect(page.getByText("0 de 10 vídeos", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
  await page.screenshot({ path: resolve(evidence, "ciclo-completo-mobile.png"), fullPage: true });
  await page.locator(".ready-card > button").click();
  await expect(page.getByRole("button",{name:"Continuar para Google/YouTube"})).toBeVisible();
  await page.screenshot({path:resolve(evidence,"consentimento-youtube-mobile.png"),fullPage:true});
  await page.getByRole("button",{name:"Cancelar criação"}).click();
  // External credentials are intentionally replaced only for this UI export contract.
  let exported = false;
  await page.route("**/dashboard", async (route) => {
    const response = await route.fetch(); const data = await response.json(); data.viewer.youtubeConnected = true;
    if (exported) data.readyRounds[0].export = { status: "SUCCESS", playlistId: "e2e-private-playlist" };
    await route.fulfill({ response, json: data });
  });
  await page.route("**/rounds/*/export", async (route) => { expect(route.request().method()).toBe("POST"); exported = true; await route.fulfill({ json: { playlistId: "e2e-private-playlist" } }); });
  await page.reload(); await expect(page.locator(".ready-card > button")).toHaveText("Criar playlist");
  await page.getByText("Ver os 10 vídeos, autores e horários", { exact: true }).click();
  await expect(page.locator(".cycle-details").getByRole("button", { name: "Criar playlist" })).toHaveCount(2);
  await page.screenshot({ path: resolve(evidence, "compartilhar-playlist-mobile.png"), fullPage: true });
  await page.locator(".ready-card > button").click();
  await expect(page.getByRole("dialog", {name:"Criação de playlist"})).toBeVisible();
  await page.getByRole("button",{name:"Confirmar criação"}).click();
  await expect(page.getByRole("link", { name: "Abrir no YouTube" })).toHaveAttribute("href", "https://www.youtube.com/playlist?list=e2e-private-playlist");
  await expect(page.getByRole("button", { name: "Acompanhar reprodução" })).toBeVisible();
  await page.getByRole("button", { name: "Acompanhar reprodução" }).click();
  await expect(page.getByRole("dialog", { name: "Acompanhar reprodução" })).toBeVisible();
  await expect(page.getByText("0% concluído")).toBeVisible();
  await page.getByRole("button", { name: "Fechar acompanhamento" }).click();
  expect(exported).toBe(true);
  // Simulate the Google round-trip, keeping the real local consent intent and automatic return flow.
  exported = false;
  let oauthConnected = false, authRound = "";
  await page.unroute("**/dashboard");
  await page.route("**/dashboard", async (route) => { const response=await route.fetch(); const data=await response.json(); data.viewer.youtubeConnected=oauthConnected; if(exported) data.readyRounds[0].export={status:"SUCCESS",playlistId:"e2e-private-playlist"}; await route.fulfill({response,json:data}); });
  await page.route("**/youtube/connect?**",async (route) => { authRound=new URL(route.request().url()).searchParams.get("roundId")!; expect(authRound).toBeTruthy(); oauthConnected=true; await route.fulfill({json:{url:`http://127.0.0.1:17517/?youtube=connected&round=${authRound}`}}); });
  await page.reload(); await page.locator(".ready-card > button").click();
  await page.getByRole("button",{name:"Continuar para Google/YouTube"}).click();
  await expect(page.getByRole("link",{name:"Abrir no YouTube"})).toBeVisible();
  expect(exported).toBe(true);
  expect(await page.evaluate(() => sessionStorage.getItem("conexao_creation_intent"))).toBeNull();
  expect(page.url()).not.toContain("youtube=connected");

  expect(errors).toEqual([]);
});
